config/routes.rb
Rails.application.routes.draw do
  resources :life
  resources :want_to_dos
  resources :last_meals
  resources :goals
    get 'goals/:copy_from/copy', :to => 'goals#new', :as => 'copy_goal'
  resources :page_selfies
  namespace :admin do
    root to: "top#index" , :as => "top"
    resources :users
    resources :diets
    resources :feelings
    resources :conditions
    resources :equipment
    resources :parts do
      get "search", to: "parts#search", on: :collection
    end
    resources :modes
    resources :food_categories
    resources :foods do
      collection { get "search"}
    end
    get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
    resources :items do
      collection { get "search"}
      collection { post :import }
    end
    resources :tips
    resources :tip_recommendations
    resources :tip_categories
  end

  resources :feelings
  resources :conditions
  resources :equipment
  resources :parts do
    get "search", to: "parts#search", on: :collection
  end
  resources :modes
  resources :food_categories
  resources :foods do
    member { patch :like, :unlike }
    collection { get "search"}
    collection { get "voted"}
  end
  get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
  resources :items do
    member { patch :like, :unlike }
    collection { get "voted"}
    collection { get "search"}
    collection { post :import }
  end
  
  resources :users ,only: [:create, :destroy ,:show ]  do
    resources :pages do
      resources :lines
      collection { get :training_only,:training_only_note ,:hidden_training,:only_chart}
      collection { post :import }
    end
  end
  resource :session , only: [:create ,  :destroy]
  get '/auth/:provider/callback',    to: 'users#create',       as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure', as: :auth_failurematch
  get 'signout', to: 'users#destroy', as: 'signout'
  root :to => 'welcome#index', :as => 'root'
  get "about" => "welcome#about", as: "about"
  get "developer" => "welcome#developer", as: "developer"
  resources :analysis do
    collection { get :dash_bord,:health,:size,:weight,:water,:feel,
                 :diet,:gym,:home,:pie_parts,:pie_place,:diet_recent,:weight_recent}
  end
  resources :maintenance do
    collection {get :pages_delete_all,:items_delete_all,:foods_delete_all,:goals_delete_all}
    collection { post :pages_import,:items_import,:foods_import,:goals_import}
  end
  resources :lines do
    collection { post :import }
  end
  resources :pages do
    resources :lines
    collection { get :training_only,
      :selfy_only,:show_pic,
      :hidden_training,:only_chart,
      :latest_page}
    collection { post :import }
  end
  resources :page_images
  resources :trainings

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :login_required
  before_action :set_training, only: [:show, :edit, :update, :destroy]

  # GET /trainings
  # GET /trainings.json
  def index
    @trainings = Training.default_order
    #@items = Item.all.sample 3  # yuta teacher
    ##全身バランスよく鍛えるように！これならいいね
    @items = [] #初期化はいるな。nil << はできないから。
    @items << Item.on_chest.sample
    @items << Item.on_backs.sample
    @items << Item.on_legs.sample

    require "sparql/client"
    client = SPARQL::Client.new("http://ja.dbpedia.org/sparql")
    results = client.query("
      SELECT DISTINCT ?label ?comment 
      WHERE {
      ?s dcterms:subject  <http://ja.dbpedia.org/resource/Category:トレーニング法>; 
      rdfs:label ?label .
      ?s rdfs:comment ?comment .
             }
       ")
    @sparql_data = results 

  end

  # GET /trainings/1
  # GET /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
      @training = Training.new :num => Training.get_now_num
  end

  # GET /trainings/1/edit
  def edit
  end

  # POST /trainings
  # POST /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to @training, notice: 'Training was successfully created.' }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1
  # PATCH/PUT /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to @training, notice: 'Training was successfully updated.' }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1
  # DELETE /trainings/1.json
  def destroy
    @training.destroy
    respond_to do |format|
      format.html { redirect_to trainings_url, notice: 'Training was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def training_params
      params.require(:training).permit(:item_id, :weight, :reps, :set, :mode_id, :day, :num)
    end
end

app/views/trainings/_form.html.erb
<%= form_for(@training) do |f| %>
  <% if @training.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training.errors.count, "error") %> prohibited this training from being saved:</h2>
      <ul>
      <% @training.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="day-buhin"  style="display:flex;justify-content:flex-start;" >
  <div class="field" style="padding-right:1em;">
    <%= f.label :day %><br>
    <%= f.date_select :day ,
      use_month_numbers: true %>
  </div>
  <div class="field" style="padding-right:1em;">
    <%= f.label :num %><br>
    <%= f.number_field :num ,style: "width:3em;" %>
  </div>
</div>

  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.collection_select :item_id ,
      Item.all, :id , :index_name,
        :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :reps %><br>
    <%= f.number_field :reps %>
  </div>
  <div class="field">
    <%= f.label :set %><br>
    <%= f.number_field :set %>
  </div>
  <div class="field">
    <%= f.label :mode_id %><br>
    <%= f.collection_select :mode_id ,
      Mode.all, :id , :name,
        :prompt => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trainings/edit.html.erb
<h1>Editing Training</h1>

<%= render 'form' %>

<%= link_to 'Show', @training %> |
<%= link_to 'Back', trainings_path %>

app/views/trainings/index.html.erb
<p id="notice"><%= notice %></p>

<p>
 2015/12/13 views/trainings/index にアドバイスメモを追加。メモの機能を検討する。
 </p>
 <p>
 2015/12/07 controlles/trainings... にユータ先生に教えてもらった配列のサンプルメソッドちょっと追加した。 
 </p>
 <p>
 2015/12/05 controlles/welcome... にwikipediaにアクセスするコードを追加。Sparqlちょっと書いた。
</p>

       <input type="button" value="growl" 
       class="btn btn-danger btn-block"
       onclick="$.growl({ title: 'Growl', message: 'The ' });" />
<h2>Note</h2>
<p>
<input type="button" value="記録する" class="btn btn-primary" onclick="location.href='/pages'" />    
<input type="button" value="分析する" class="btn btn-primary" onclick="location.href='/analysis'" />    
<input type="button" value="マスタ管理" class="btn btn-warning"  onclick="location.href='/items'" />
</p>

<h1>今日のおすすめメニュー</h1> 
  <% @items.each do |item| %>
    <li>
    <%= item.name %> . <%=  item.part.name  %> -> <%=  item.reps %>回
    </li>
  <% end %>

<h1>トレーニング記録一覧</h1>
<table class="table table-striped"
       style="text-align: right; width: 100%;">
  <thead>
    <tr>
      <th>Day</th>
      <th>
        Item
        Weight
        Reps
        Set
      </th>
    </tr>
  </thead>

  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.day %> . <%=  training.num  %></td>
        <td>
          <%= link_to training.item.index_name, training %>
          <%= training.weight %> kg /   
          <%= training.reps %>  
          [<%= training.set %>]  
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Training', new_training_path %>

<h1>筋力トレーニングのアドバイス・メモ</h1>
...viewにベタで書いてるけど、こういうことを整理するようにしたい。種目ごとにメモ、全体メモ？などの要素を入れる。

<h2>フルボトムスクワット</h2>

<p>
 ケツをマックス落として、立つ時にぐっと入れるイメージ。顔は常に正面。目を見る、ちょっとアゴを引くのがいい感じぽい。前後にぶれない。
 </P>

 <h2>バーベルベンチプレス</h2>
 <p>
  アーチを作り、胸を立てる。下部が上を向く。肩をリラックスして。肩を足の方に落とす。て幅は80ラインの内側に小指があたるようにして親指がわに重心。バーが固定されている、背中でベンチを押し付けるようなイメージ。
  </P>
  
 <h2>インクラインダンベルベンチプレス</h2>
 <p>
   アーチを作り、胸を立てる。ケツは浮かせないこと。垂直にダンベルを落とすけどイメージは肘が足の方奥にいく感じ。春日町のように胸を開くことが大事と考える。基本的にはレンジをひろくとる。
 </p>

 <h2>バーベルバックプレス</h2>
 <p>
    肩のラインから、横から見た時に一直線にバーベルをあげる。バーベルの持つ位置はフィニッシュで直角に肘がなる幅。首を前にスライドして後頭部を擦るイメージ。肘を前に出す、肘と前腕が垂直方向に動くことを強制すると考える
 </p>

 <h2>ハーフ？デッドリフト</h2>
 <p>
     パワーグリップはちゃんと巻く。ストラップ同様ギチギチにする！ゴム第２枚重ねにすると足はば広げすぎず、底上げできるのでよい。スタートは断ち切ったところで胸をはり。ケツを閉めて。そこから下げて戻す。脛が擦るイメージ。ケツをぐっと入れるイメージ。スコンスコンと早いイメージ、工場のピストンのイメージと自分は考える
 </p>

 <h2>アレンジプルアップ</h2>
 <p>アシストマシン専用。膝は後ろめ。肩幅より少し広めで握り。腕は伸ばしきらないとこまで落とす。背中のテンション感じるところで、肩をすくめ胸を入れて、さらに広背筋の外側？脇の下？のストレッチをさせるテンション感じるのが大事と考える。ちゃんと胸を突き上げるイメージしないといけないので気をつける
 </p>
 
 <h2>EZバーアームカール</h2>
 <p>
 肘は基本的には位置を固定する。やや前傾姿勢で背中で引かないこと、まっすぐ上にあげる。上体で向かいにいく「前かがみきみ〕
 </p>

<h2>etc</h2>
<p>
7種目。ビッグ3を中心に考える。時間とパワー配分は。スクワットは腰の負担もあるけど高重量すぎないところで追い込む10〜15?
       サブ種目などは多少バリエーション加える。けど取り敢えず上記7つをきっちり、トラディショナルなやり方で、ストリクトにオーバロードの原則でやる。基本の基本。
</p>

<h2>Infomaiton</h2>
<div class="alert alert-success" style="padding-left: 3em;">
  <strong>Info!</strong> Wikipedeaからリアルタイムに取得したトレニーング方法をご紹介します。
</div>

<a href="http://ja.dbpedia.org/">wikipediaからRuby on Railsでデータ取得する方法はこちら</a>
<% @sparql_data.each do |solution| %>
  <h2><%= solution[:label] %></h2>
  <p><%=solution[:comment] %></p>
<%  end  %>

app/views/trainings/new.html.erb
<h1>New Training</h1>

<%= render 'form' %>

<%= link_to 'Back', trainings_path %>

app/views/trainings/show.html.erb
<p id="notice"><%= notice %></p>

<%= @training.day %>.<%= @training.num  %>
<p>
  <strong>Item:</strong>
  <%= @training.item.index_name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @training.weight %>
</p>

<p>
  <strong>Reps:</strong>
  <%= @training.reps %>
</p>

<p>
  <strong>Set:</strong>
  <%= @training.set %>
</p>

<p>
<strong>Mode:</strong>
<% if @training.mode_id != nil %>
  <%= @training.mode.name  %>
<%end%>
</p>

<%= link_to 'Edit', edit_training_path(@training) %> |
<%= link_to 'Back', trainings_path %> |
<%= link_to 'Destroy', @training, method: :delete, data: { confirm: 'Are you sure?' } %>