config/routes.rb
Rails.application.routes.draw do
  resources :life
  resources :want_to_dos
  resources :last_meals
  resources :goals
    get 'goals/:copy_from/copy', :to => 'goals#new', :as => 'copy_goal'
  resources :page_selfies
  namespace :admin do
    root to: "top#index" , :as => "top"
    resources :users
    resources :diets
    resources :feelings
    resources :conditions
    resources :equipment
    resources :parts do
      get "search", to: "parts#search", on: :collection
    end
    resources :modes
    resources :food_categories
    resources :foods do
      collection { get "search"}
    end
    get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
    resources :items do
      collection { get "search"}
      collection { post :import }
    end
    resources :tips
    resources :tip_recommendations
    resources :tip_categories
  end

  resources :feelings
  resources :conditions
  resources :equipment
  resources :parts do
    get "search", to: "parts#search", on: :collection
  end
  resources :modes
  resources :food_categories
  resources :foods do
    member { patch :like, :unlike }
    collection { get "search"}
    collection { get "voted"}
  end
  get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
  resources :items do
    member { patch :like, :unlike }
    collection { get "voted"}
    collection { get "search"}
    collection { post :import }
  end
  
  resources :users ,only: [:create, :destroy ,:show ]  do
    resources :pages do
      resources :lines
      collection { get :training_only,:training_only_note ,:hidden_training,:only_chart}
      collection { post :import }
    end
  end
  resource :session , only: [:create ,  :destroy]
  get '/auth/:provider/callback',    to: 'users#create',       as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure', as: :auth_failurematch
  get 'signout', to: 'users#destroy', as: 'signout'
  root :to => 'welcome#index', :as => 'root'
  get "about" => "welcome#about", as: "about"
  get "developer" => "welcome#developer", as: "developer"
  resources :analysis do
    collection { get :dash_bord,:health,:size,:weight,:water,:feel,
                 :diet,:gym,:home,:pie_parts,:pie_place,:diet_recent,:weight_recent}
  end
  resources :maintenance do
    collection {get :pages_delete_all,:items_delete_all,:foods_delete_all,:goals_delete_all}
    collection { post :pages_import,:items_import,:foods_import,:goals_import}
  end
  resources :lines do
    collection { post :import }
  end
  resources :pages do
    resources :lines
    collection { get :training_only,
      :selfy_only,:show_pic,
      :hidden_training,:only_chart,
      :latest_page}
    collection { post :import }
  end
  resources :page_images
  resources :trainings

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  class << self
    def search(query)
      rel = order("id")
      if query.present?
        rel = rel.where("name LIKE ? ", "%#{query}%")
      end
      rel
    end
  end
end

app/controllers/admin/equipment_controller.rb
class Admin::EquipmentController < ApplicationController
  before_action :login_required
  before_action :set_equipment, only: [:show, :edit, :update, :destroy]
  include AdminUtil
  before_action :admin_login_required
  
  # GET /equipment
  # GET /equipment.json
  def index
    @equipment = Equipment.all
    @new_equipment = Equipment.new
    @search_form = SearchForm.new(params[:search_form])
    @equipment = @equipment.search(@search_form.q) if  @search_form.q.present?
    #   respond_to do |format|
    #     format.html #index.html.erb
    #     format.json { render :index }
    #   end
  end

  def show
  end

  def new
    @equipment = Equipment.new
  end

  # GET /equipment/1/edit
  def edit
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(equipment_params)
    if @equipment.save
      status = 'success'
      html = render_to_string partial: 'show',
        locals: { equipment: @equipment }
    else
      status = 'error'
    end
    render json: { status: status, data: @equipment, html:html }

    #   respond_to do |format|
    #     if @equipment.save
    #       format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
    #       format.json { render :show, status: :created, location: @equipment }
    #     else
    #       format.html { render :new }
    #       format.json { render json: @equipment.errors, status: :unprocessable_entity }
    #     end
    #   end
  end

  # PATCH/PUT /equipment/1
  # PATCH/PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])
    if @equipment.update(equipment_params)
      status = 'success'
    else
      status = 'error'
    end
    render json: {status: status ,data: @equipment }
    #  respond_to do |format|
    #     if @equipment.update(equipment_params)
    #       format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
    #       format.json { render :show, status: :ok, location: @equipment }
    #     else
    #       format.html { render :edit }
    #       format.json { render json: @equipment.errors, status: :unprocessable_entity }
    #     end
    #   end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment.destroy
    render json: {status: 'success' ,data: @equipment }
    #  respond_to do |format|
    #    format.html { redirect_to equipment_index_url, notice: 'Equipment was successfully destroyed.' }
    #    format.json { head :no_content }
    #  end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_equipment
    @equipment = Equipment.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def equipment_params
    params.require(:equipment).permit(:name)
  end
end

app/views/admin/equipment/_form.html.erb
<%= form_for([:admin,@equipment]) do |f| %>
  <% if @equipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@equipment.errors.count, "error") %> prohibited this equipment from being saved:</h2>

      <ul>
      <% @equipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/equipment/_form2.html.erb
<%= form_for([:admin,equipment] , remote: true) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name ,id: nil,class: 'body' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/equipment/_show.html.erb
<div class="equipment" >
  <div class="viewr" >
    <%= equipment.id %>.
    <span class="body"><%= equipment.name %></span>
    <%= button_tag '編集' ,class: 'edit' ,type: :button %>
  </div>
  <div class="editor">
    <div>
      <%= button_tag 'キャンセル',class: 'cancel' , type: :button %>
    </div>
    <%= render 'form2' , equipment: equipment %>
    <%= form_for [:admin,equipment], method: :delete, remote: true,
      html:{ id: nil,class: 'delete_equipment' } do |f| %>
      <%= f.submit '削除' %>
    <% end %>
  </div>
</div>

app/views/admin/equipment/edit.html.erb
<h1>Editing Equipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @equipment %> |
<%= link_to 'Back', equipment_index_path %>

app/views/admin/equipment/index.html.erb
<p id="notice"><%= notice %></p>

<h1>トレーニング器具一覧</h1>
<a href="http://ginpen.com/2011/11/28/ajax-on-rails/">ajaxのCRUD参考サイト</a>
<div id="equipments">
  <% @equipment.each do |equipment| %>
    <%= render 'show' , equipment: equipment %>
  <% end %>
</div>

<br/>

<h1> トレーニング器具 追加 </h1>
<%= render 'form2' , equipment: @new_equipment, submit_text: '新規' %>

<%= link_to '管理ページに戻る', admin_top_path %>

app/views/admin/equipment/index.js.erb
alert(' <%= @equipment.size %>');

$('#equipments').html('<% @equipment.each do |equipment| %><%= render 'show' ,equipment: equipment  %><% end %>');

app/views/admin/equipment/new.html.erb
<h1>New Equipment</h1>

<%= render 'form' %>

<%= link_to 'Back', equipment_index_path %>

app/views/admin/equipment/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @equipment.name %>
</p>

<%= link_to 'Edit', edit_equipment_path(@equipment) %> |
<%= link_to 'Back', equipment_index_path %>