config/routes.rb
Rails.application.routes.draw do
  resources :life
  resources :want_to_dos
  resources :last_meals
  resources :goals
    get 'goals/:copy_from/copy', :to => 'goals#new', :as => 'copy_goal'
  resources :page_selfies
  namespace :admin do
    root to: "top#index" , :as => "top"
    resources :users
    resources :diets
    resources :feelings
    resources :conditions
    resources :equipment
    resources :parts do
      get "search", to: "parts#search", on: :collection
    end
    resources :modes
    resources :food_categories
    resources :foods do
      collection { get "search"}
    end
    get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
    resources :items do
      collection { get "search"}
      collection { post :import }
    end
    resources :tips
    resources :tip_recommendations
    resources :tip_categories
  end

  resources :feelings
  resources :conditions
  resources :equipment
  resources :parts do
    get "search", to: "parts#search", on: :collection
  end
  resources :modes
  resources :food_categories
  resources :foods do
    member { patch :like, :unlike }
    collection { get "search"}
    collection { get "voted"}
  end
  get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
  resources :items do
    member { patch :like, :unlike }
    collection { get "voted"}
    collection { get "search"}
    collection { post :import }
  end
  
  resources :users ,only: [:create, :destroy ,:show ]  do
    resources :pages do
      resources :lines
      collection { get :training_only,:training_only_note ,:hidden_training,:only_chart}
      collection { post :import }
    end
  end
  resource :session , only: [:create ,  :destroy]
  get '/auth/:provider/callback',    to: 'users#create',       as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure', as: :auth_failurematch
  get 'signout', to: 'users#destroy', as: 'signout'
  root :to => 'welcome#index', :as => 'root'
  get "about" => "welcome#about", as: "about"
  get "developer" => "welcome#developer", as: "developer"
  resources :analysis do
    collection { get :dash_bord,:health,:size,:weight,:water,:feel,
                 :diet,:gym,:home,:pie_parts,:pie_place,:diet_recent,:weight_recent}
  end
  resources :maintenance do
    collection {get :pages_delete_all,:items_delete_all,:foods_delete_all,:goals_delete_all}
    collection { post :pages_import,:items_import,:foods_import,:goals_import}
  end
  resources :lines do
    collection { post :import }
  end
  resources :pages do
    resources :lines
    collection { get :training_only,
      :selfy_only,:show_pic,
      :hidden_training,:only_chart,
      :latest_page}
    collection { post :import }
  end
  resources :page_images
  resources :trainings

end

app/models/tip.rb
class Tip < ActiveRecord::Base
  belongs_to :tip_category
  belongs_to :tip_recommendation

class <<self
  def random_one
    tip = Tip.new
    #rondom １件 http://easyramble.com/get-record-randomly-with-active-record.html
    if Tip.count > 0
     tip = Tip.where( 'id >= ?', rand(Tip.first.id..Tip.last.id) ).first
    end
  end
end
  def grol_mes
    mes = tip_category.name + ":" + star + "　　　　"
    mes += description.gsub(/\r\n|\r|\n/, ",")
  end
  def star
    star = ""
    tip_recommendation.rate.times do
      star += "⭐️"
    end
    star
  end
end

app/controllers/admin/tips_controller.rb
class Admin::TipsController < InheritedResources::Base
  include AdminUtil
  before_action :login_required
  before_action :admin_login_required
  before_action :growl_setup ,only:[:index]
  private
  def growl_setup
    @tip = Tip.random_one
  end
  def tip_params
    params.require(:tip).permit(:tip_category_id, :tip_recommendation_id, :name, :description, :author)
  end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/admin/tips/_form.html.erb
<%= form_for([:admin,@tip]) do |f| %>
  <% if @tip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>
      <ul>
      <% @tip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name , { class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :tip_category_id %><br>
    <%= f.collection_select :tip_category_id ,
      TipCategory.all.order(:id), :id , :name ,
      {prompt: true} , { class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :tip_recommendation_id %><br>
    <%= f.collection_select :tip_recommendation_id ,
      TipRecommendation.all.order(:id), :id , :name ,
      {prompt: true} , { class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description , { class: "form-control",cols: 5,rows: 5,style: "width:100%;"} %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author , { class: "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/tips/edit.html.erb
<h1>ヒント 編集</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_tip_path(@tip) %> |
<%= link_to 'Back', admin_tips_path %>

app/views/admin/tips/index.html.erb
<style>table th {text-align:center;} </style>
<p id="notice"><%= notice %></p>
<%= render "shared/tipgrowl" %>
<h1>ヒント一覧</h1>

<table class="table table-striped"
style="text-align: right; width: 100%;">
<thead>
  <tr>
    <th>カテゴリ</th>
    <th>オススメ度</th>
    <th>タイトル</th>
    <th></th>
  </tr>
</thead>

<tbody>
  <% @tips.each do |tip| %>
  <tr>
    <td><%= link_to tip.tip_category.name , admin_tip_path(tip)%></td>
    <td>
      <% tip.tip_recommendation.rate.times do %>
      ⭐️
      <% end %>
    </td>
    <td><%= link_to tip.name ,admin_tip_path(tip) %></td>
    <td>
      <%= link_to '参照', admin_tip_path(tip) ,class: "btn btn-default" %>
      <%= link_to '編集', edit_admin_tip_path(tip) ,class: "btn btn-default" %>
      <%= link_to '削除', admin_tip_path(tip), method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-default" %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>

<br>

<%= link_to '新規作成', new_admin_tip_path ,class: "btn btn-default" %>

<%= link_to '管理ページに戻る', admin_top_path %>

app/views/admin/tips/new.html.erb
<h1>新規 ヒント</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_tips_path %>

app/views/admin/tips/show.html.erb
<%= render "shared/tipgrowl" %>
<p id="notice"><%= notice %></p>

<p>
  <strong title="Name">タイトル:</strong>
  <%= @tip.name %>
</p>

<p>
  <strong title="Tip category">カテゴリ:</strong>
  <%= @tip.tip_category.name %>
</p>

<p>
  <strong titele="Tip recommendation">オススメ度:</strong>
  <% @tip.tip_recommendation.rate.times do %>
   ⭐️
   <% end %>:
  <%= @tip.tip_recommendation.name %>
</p>

<p>
  <strong title="Description">説明:</strong>
  <pre>
  <%= raw @tip.description %>
 </pre>
</p>

<p>
  <strong title="Author">提供者:</strong>
  <%= @tip.author %>
</p>

<%= link_to 'Edit', edit_admin_tip_path(@tip) %> |
<%= link_to 'Back', admin_tips_path %>