config/routes.rb
Rails.application.routes.draw do
  resources :life
  resources :want_to_dos
  resources :last_meals
  resources :goals
    get 'goals/:copy_from/copy', :to => 'goals#new', :as => 'copy_goal'
  resources :page_selfies
  namespace :admin do
    root to: "top#index" , :as => "top"
    resources :users
    resources :diets
    resources :feelings
    resources :conditions
    resources :equipment
    resources :parts do
      get "search", to: "parts#search", on: :collection
    end
    resources :modes
    resources :food_categories
    resources :foods do
      collection { get "search"}
    end
    get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
    resources :items do
      collection { get "search"}
      collection { post :import }
    end
    resources :tips
    resources :tip_recommendations
    resources :tip_categories
  end

  resources :feelings
  resources :conditions
  resources :equipment
  resources :parts do
    get "search", to: "parts#search", on: :collection
  end
  resources :modes
  resources :food_categories
  resources :foods do
    member { patch :like, :unlike }
    collection { get "search"}
    collection { get "voted"}
  end
  get 'foods/:copy_from/copy', :to => 'foods#new', :as => 'copy_food'
  resources :items do
    member { patch :like, :unlike }
    collection { get "voted"}
    collection { get "search"}
    collection { post :import }
  end
  
  resources :users ,only: [:create, :destroy ,:show ]  do
    resources :pages do
      resources :lines
      collection { get :training_only,:training_only_note ,:hidden_training,:only_chart}
      collection { post :import }
    end
  end
  resource :session , only: [:create ,  :destroy]
  get '/auth/:provider/callback',    to: 'users#create',       as: :auth_callback
  get '/auth/failure',               to: 'users#auth_failure', as: :auth_failurematch
  get 'signout', to: 'users#destroy', as: 'signout'
  root :to => 'welcome#index', :as => 'root'
  get "about" => "welcome#about", as: "about"
  get "developer" => "welcome#developer", as: "developer"
  resources :analysis do
    collection { get :dash_bord,:health,:size,:weight,:water,:feel,
                 :diet,:gym,:home,:pie_parts,:pie_place,:diet_recent,:weight_recent}
  end
  resources :maintenance do
    collection {get :pages_delete_all,:items_delete_all,:foods_delete_all,:goals_delete_all}
    collection { post :pages_import,:items_import,:foods_import,:goals_import}
  end
  resources :lines do
    collection { post :import }
  end
  resources :pages do
    resources :lines
    collection { get :training_only,
      :selfy_only,:show_pic,
      :hidden_training,:only_chart,
      :latest_page}
    collection { post :import }
  end
  resources :page_images
  resources :trainings

end

app/models/last_meal.rb
class LastMeal < ActiveRecord::Base
  belongs_to :user
  belongs_to :food
end

app/controllers/last_meals_controller.rb
class LastMealsController < InheritedResources::Base

  private

    def last_meal_params
      params.require(:last_meal).permit(:user_id, :food_id, :date, :memo)
    end
end

app/helpers/last_meals_helper.rb
module LastMealsHelper
end

app/views/last_meals/_form.html.erb
<%= form_for(@last_meal) do |f| %>
  <% if @last_meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@last_meal.errors.count, "error") %> prohibited this last_meal from being saved:</h2>

      <ul>
      <% @last_meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id , { class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :food_id %><br>
    <%= f.text_field :food_id , { class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date , { class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_field :memo , { class: "form-control"} %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/last_meals/edit.html.erb
<h1>Editing Last Meal</h1>

<%= render 'form' %>

<%= link_to '参照', @last_meal ,class: "btn btn-default"%> |
<%= link_to '戻る', last_meals_path ,class: "btn btn-default" %>

app/views/last_meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Last Meals</h1>

<table class="table table-striped"
style="text-align: left; width: 100%;">
  <thead>
    <tr>
      <th>User</th>
      <th>Food</th>
      <th>Date</th>
      <th>Memo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @last_meals.each do |last_meal| %>
      <tr>
        <td><%= last_meal.user.name %></td>
        <td><%= last_meal.food.name %></td>
        <td><%= last_meal.date %></td>
        <td><%= last_meal.memo %></td>
        <td>
      <%= link_to '参照', last_meal ,class: "btn btn-default" %>
      <%= link_to '編集', edit_last_meal_path(last_meal) ,class: "btn btn-default" %>
      <%= link_to '削除', last_meal_path(last_meal) , method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-default" %>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_last_meal_path , class: "btn btn-default" %>

app/views/last_meals/new.html.erb
<h1>New Last Meal</h1>

<%= render 'form' %>

<%= link_to '戻る', last_meals_path ,class: "btn btn-default" %>

app/views/last_meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @last_meal.user.name %>
</p>

<p>
  <strong>Food:</strong>
  <%= @last_meal.food.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @last_meal.date %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @last_meal.memo %>
</p>

<%= link_to '編集', edit_last_meal_path(@last_meal) ,class: "btn btn-default"%> |
<%= link_to '戻る', last_meals_path ,class: "btn btn-default" %>